---
output: 
  word_document:
    reference_docx: "template.docx"
date: "`r lubridate::today()`"
---

Hamblin Pond neighbors,

Over the past several months, a research team from the US Environmental Protection Agency (USEPA) has been coordinating with the Barnstable Clean Water Coalition (BCWC) and the Town of Barnstable to begin a research project in both Shubael and Hamblin Ponds.  We wanted to provide you with a little more information as well as some contacts in case you have more questions.  

The USEPA team started sampling early this summer. The most conspicuous part of their effort is the yellow water quality buoys moored near the center of each pond.  They were deployed on June 10th and will remain until early November.  The buoy should not impact your use of the pond.  If you are curious you may certainly take a look at the buoy, but the USEPA team does ask that you stay a few feet from the buoy if you are out near it.

In addition to the buoy, the USEPA team will be on site 1-2 times per month collecting water samples and taking other measurements.  Also, BCWC will be flying a drone on a regular basis at Shubael Pond to collect additional data for HAB monitoring. These data will be processed by USEPA as part of this project. The goals with this work will be to better understand Harmful Algal Blooms (HABs) in general while also providing information specific to each of these two ponds.

For a better understanding of Harmful Algal Blooms in general look at the US EPA's Cyanobacterial HABs site: <https://www.epa.gov/cyanohabs>.  If you have questions about details of the work in Shubael and Hamblin ponds please don't hesitate to contact the USEPA project leads, Stephen Shivers (shivers.stephen@epa.gov) and Jeff Hollister (hollister.jeff@epa.gov).  Also, the USEPA team would be happy to discuss their work after they have collected some data.  Stay tuned for details on that in the near future.

